version = 0.1
[default.deploy.parameters]
stack_name = "get-visitor-app"
resolve_s3 = true
s3_prefix = "get-visitor-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
