AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  VisitorGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: visitorGet
      CodeUri: /getVisitor.zip
      Runtime: python3.10
      PackageType: Zip
      Handler: getVisitor.lambda_handler
      RolePath: /
      Policies:
        - S3ReadPolicy:
            BucketName: cumuluscompendium
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorTable
        - CloudWatchPutMetricPolicy: {}
      Events:
        VisitorGetAPI:
          Type: Api
          Properties:
            Method: get
            Path: /path
            RestApiId:
              Ref: VisitorGetAPI

  VisitorGetAPI:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: REGIONAL
      StageName: Prod
      Cors:
       AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
       AllowMethods: "'GET,OPTIONS'"
       AllowOrigin: "'*'"

  VisitorTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: VisitorTable
      PrimaryKey: 
        Name: Key_id
        Type: String
